apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  type: LoadBalancer
  ports:
  - port: 4499
    targetPort: 4499
    name: http
  - port: 443
    targetPort: 4499
    name: http
  selector:
    app: wisecow
